### ISSUE TITLE
Adjust ZeroMorph for EvaluationEngineTrait

### ISSUE THREAD

**Issue by emmorais** [lurk-lab/arecibo#19]
KZG is a building block that allows us to commit to univariate polynomials. ZeroMorph uses that building block to construct a commitment to multilinear polynomials, which can be used by Nova. 

Part of the interfaces are already prepared for this trait, since polynomials and input points are represented as &[Fr], and the evaluation of this polynomial at this point is &Fr.

However, other adjustments are necessary. Namely, take a look on things like CommitmentEngineTrait, CommitmentKey, ProverKey, VerifierKey, etc.

**Comment by huitseeker** [comment]
current attempts in https://github.com/lurk-lab/arecibo/tree/zeromorph_replacement and https://github.com/lurk-lab/arecibo/tree/evaluation_engine

**Comment by huitseeker** [comment]
Closed in #71
