### ISSUE TITLE
Use common serialisation format for Pasta and Grumping curves

### ISSUE THREAD

**Issue by storojs72** [lurk-lab/arecibo#20]
Field elements from proof / public parameters currently a being serialised differently depending on curve. For example for Pasta curves we have:
```
"digest":"64288c7ef43914fee16e90774bebe8727d734b28c9cee7c0b35e97a0c27efd02"
``` 
while for Grumpkin:
```
"digest":[560067867113498870,9482374276275323153,13618845702275708329,2842217616396256311]
```

If there are no actual reasons, the first (Pasta) variant of serialisation is preferable to use as soon as it doesn't require to perform elaborated Montgomery reduction while importing the field element. Our [verifier](https://github.com/lurk-lab/solidity-verifier) uses data loader, sharpened for Pasta variant, which, for correct uint256 import into Solidity environment, requires just item reversing.

The serialisation that I used for testing was added with the following code ([here](https://github.com/lurk-lab/Nova/blob/dev/src/lib.rs#L1205)):

```
// serialize compressed snark
let serialized_compressed_snark = serde_json::to_string(&compressed_snark).unwrap();
std::fs::write(std::path::Path::new("compressed-snark-grumpkin.json"), serialized_compressed_snark).expect("Unable to write file");

// serialize verifier key
let serialized_vk = serde_json::to_string(&vk).unwrap();
std::fs::write(std::path::Path::new("verifier-key-grumpkin.json"), serialized_vk).expect("Unable to write file");
```

**Comment by huitseeker** [comment]
Dealt with in https://github.com/privacy-scaling-explorations/halo2curves/pull/85
We might use a patch to a lurk-lab copy of that branch in the future. WDYT @storojs72 ?

**Comment by storojs72** [comment]
Yes. For now, I'm using [branch](https://github.com/huitseeker/halo2curves/tree/field_serialization) from your fork and it works pretty well. As far as I understand, the PR (https://github.com/privacy-scaling-explorations/halo2curves/pull/85) is on hold until some RFC discussion happens (which doesn't depend on us), but we can have the necessary change in Arecibo and treating it as a reference for our solidity verifier.

**Comment by storojs72** [comment]
BTW, another thing, that I would like to have from solidity verifier's perspective - is serialising points in Affine representation (2 coordinates) instead of Montgomery (3 coordinates). So far, while working on Grumpkin-based e2e contract (https://github.com/lurk-lab/solidity-verifier/commits/grumpkin), I noticed that no computations require points in Montgomery form (I don't know whether Zeromorph stuff will require Montgomery points), so it would be nice to avoid any kind of points' data manipulations (decompression - if it is serialised as compressed one, or conversion - if it is serialised as Montgomery point, which is a case currently) at Solidity side in order to reduce the gas cost. 

Can we may be submit a PR to Arecibo?

**Comment by huitseeker** [comment]
see https://github.com/privacy-scaling-explorations/halo2curves/pull/88

**Comment by huitseeker** [comment]
This will close when halo2curves releases their next version (post 0.4.0)
