### ISSUE TITLE
feat: create test vectors & benchmark for PCS

### ISSUE THREAD

**Issue by adr1anh** [lurk-lab/arecibo#212]
A multi-linear polynomial commitment scheme is parametrized by 
- Number of variables $n$
- A polynomial `P` $P(X_1,\ldots,X_n)$ given as `Vec<F>` of size $2^n$
- An evaluation point `x` $\vec{x} = (x_1,\ldots,x_n)$ given as `Vec<F>` of size $n$.
- The commitment `C` $C = \mathsf{Commit}(P)$
- The evaluation `e` $e = P(\vec{x})$

The goal is to support generating sampling these parameters in order to derive test vectors (along with the `EvaluationArgument` proofs) for testing in Solidity, as well as benchmarking of the relative performance of different PCS `EvaluationEngine` (in particular `mlzkg` vs `zeromorph`). 

- Implement support for generating random instances of polynomials and evaluation points, and derive both valid and invalid commitments and evaluations.
- Fix a seed and generate serializable vectors of the above data, and a proof for each PCS engine.
- Write a benchmark comparing `mlkzg::EvaluationEngine`, `non_hiding_zero_morph::ZMPCS` and `ipa_pcs::EvaluationEngine` in terms of 
  - Proof size
  - Prover time
  - Verifier time

**Comment by tchataigner** [comment]
Hey all! Happy new year! I've already produced the [generic test methods](https://github.com/tchataigner/arecibo/blob/feature/test-ipa/src/provider/util/mod.rs#L6-L144) along with the [start of a benchmark](https://github.com/tchataigner/arecibo/blob/feature/test-ipa/benches/pcs.rs). 

Refactoring aside, I have some questions about how I did thing:
- I wanted to create a generic test function to assert that `verify` would fail on an unvalid proof. This resulted in [`test_fail_bad_proof`](https://github.com/tchataigner/arecibo/blob/feature/test-ipa/src/provider/util/mod.rs#L104-L143). However, I'm not really sure that what I did is valid way to do so, either on the actual implementation or on the heaviness of the code. What is your opinion?
- In the benchmarks and my test, I currently iteretate over three seeds : 4, 5 ,6. I re-used them from a previous test in MLKZG. I was wondering if you had more precise directions on how many I should run and of which order for the different PCS?

**Comment by adr1anh** [comment]
Thanks for taking up this issue! Will take a deeper look later, but let me answer your questions first. 

- In general, generating failing cases can be tricky since there are a lot of parameters that can be tweaked to produce and invalid proof. In this case, modifying the opening point should indeed guarantee that the proof is invalid. Other strategies could include
  - Modifying the commitment, the evaluation, or any of the polynomial's coefficients before feeding it into the `prove` method
  - Twiddling some of the field in the PCS proof, though this would not be generic over all the implementations
- Being able to create these test-vectors deterministically is great! My only suggestion would be to pass along an `Rng` object rather than a fixed `seed`. This enables sampling both deterministic elements and fully random ones by using the system RNG. I would say that the `seed` is derived from the `num_variables`, and that this latter quantity should be passed along to the methods performing the sampling, alongside the initialized `rng`. 
- I think a more "natural" flow (in terms of emulating the real protocols) would look like:
  - "Sample" a  `CommitmentKey`
    - I don't think we want to actually sample here though, since there should be only one fixed `CommitmentKey` per maximum polynomial size. Ideally, we would just read it from disk.
  - Sample `poly` and `point` using (possibly seeded) `rng`
  - Commit to and evaluate `poly` at `point`
  - Return `(poly, comm, point, eval)` so that it can be serialized as a test vector 
  - Run the prover/verifier 
    - Initialize transcript and add `comm, point, eval`. 
    - Create proof 
    - verify the proof 
    - return the proof for serialization as part of the test data. 
- The maximum size of the polynomials we are opening would be `ell = 24`, though this will be very expensive and I don't think we actually have circuits as big. The Lurk circuit is approximately `12'000` constraints, corresponding to `ell = 13` or `14`. I think `ell=20` would be an okay upper but only if we can make sure the benches don't run for every CI push.

**Comment by huitseeker** [comment]
> "Sample" a CommitmentKey

for the pairing-based PCSes, the commitment keys have a `gen_srs_for_testing` function you can use. For the IPA, the default constructor is fine (look for uses of `from_label` and use a label that clearly marks a test).

**Comment by tchataigner** [comment]
@huitseeker, I was lucky since when generating the commitment key I leverage the `setup` method that seems to already use `gen_srs_for_testing` for pairing-based PCSes and `from_label` for IPA. I guess I have to thanks preivous devs for that :smile:

**Comment by huitseeker** [comment]
Closed in #222
