### ISSUE TITLE
ci: Crate docs action not working

### ISSUE THREAD

**Issue by samuelburnham** [lurk-lab/arecibo#247]
From the errors below, the action seems to need a nightly toolchain and fix some doc links.

Failing run: https://github.com/lurk-lab/arecibo/actions/runs/7455356190/job/20284299252

**Comment by huitseeker** [comment]
Fixed in https://github.com/lurk-lab/ci-workflows/pull/22
good run at https://github.com/lurk-lab/arecibo/actions/runs/7549231360
