### ISSUE TITLE
CUDA acceleration always enabled regardless of `cuda` feature enabled

### ISSUE THREAD

**Issue by samuelburnham** [lurk-lab/arecibo#259]
There have been multiple reports of consistent GPU utilization shown with `nvtop` on Nvidia machines, regardless of if the `cuda`/`opencl` features are enabled. However, there should be no CUDA usage if the feature isn't enabled.

According to @winston-h-zhang this may be due to the following issue in https://github.com/lurk-lab/grumpkin-msm and https://github.com/supranational/pasta-msm:
> build.rs will always enable cuda if it detects a valid nvcc

**Comment by huitseeker** [comment]
Sam's results:
https://gist.github.com/huitseeker/b1b567f2aa4396796cd9bd9ea564a1e4
w/o the non-asm run:
https://gist.github.com/huitseeker/0a5504320bd179f07310de131f618c72

**Comment by huitseeker** [comment]
Conclusion: we should make grumpkin-msm: 
1/ always compile the CPU method, as it does now, 
2/ only attempt to compile and run the GPU method when the cuda feature is enabled 
3/ emit an indiscutably spectacular message when it's compiled with the cuda feature and does not find the CPU,

See PR at https://github.com/lurk-lab/grumpkin-msm/pull/9
