### ISSUE TITLE
How to verify proofs generated by Supernova/Nova?

### ISSUE THREAD

**Issue by flyq** [lurk-lab/arecibo#378]
After looking at some Readme files and example codes, I have some doubts about `RecursiveSNARK` and `CompressedSNARK`. They both have a `verify` method. So for the verifier, do both need to be verified? `CompressedSNARK` is generated in conjunction with proof systems such as `Spartan`. It seems that the content it contains is the real proof.

I think we lack a complete example of using nova/supernova to generate a proof, which produces a chunk of bytes. The bytes are parsed into parameters through the command line tool, and then there is an independent verifier program (rust) that accepts these parameters and outputs true/false. In fact, this is what [the circom tutorial provides](https://docs.circom.io/getting-started/proving-circuits/#verifying-from-a-smart-contract). Although they provide a Solidity verifier, I think it is enough for us to provide a rust verifier for the time being.

**Comment by mpenciak** [comment]
Sorry about the delay in reponse, I hope this helps answer your questions:

1) The `RecursiveSNARK` and `CompressedSNARK` `verify` functions serve different purposes. If you're hoping to generate a proof, and distribute it as a chunk of bytes that can be verified by others then you probably want to use the `CompressedSNARK.verify`, as it is significantly smaller and meant to be portable.

2) If you look at the implementation of `CompressedSNARK::verify` you'll see that it's very similar to `RecursiveSNARK::verify` except in the final verification step: The `RecursiveSNARK` has the full data of the witnesses, whereas in the `CompressedSNARK` setting these are replaced by polynomial commitments to the witness which the verifier must open with the help of of some prover hints.


2) The CompressedSNARK struct has derived Serde `Serialize` and `Deserialize` methods: https://github.com/lurk-lab/arecibo/blob/5268c2084821955c5953c29c7e179b2052523b5d/src/lib.rs#L792-L794
so using Arecibo as a library and calling these methods in your command line tool could achieve what you're looking for.
