### ISSUE TITLE
Manage `CommitmentKeyHint`s properly in supernova

### ISSUE THREAD

**Issue by winston-h-zhang** [lurk-lab/arecibo#53]
This is where the optfn1, optfn2 parameters from above come in. They need to be parametrized by a preference expressed as a static function of the SNARK that will eventually be used to compress the proof. See #5. We should open an issue to fix this across SuperNova.

_Originally posted by @huitseeker in https://github.com/lurk-lab/arecibo/pull/51#discussion_r1334773944_

**Comment by huitseeker** [comment]
Closed in #95
