### ISSUE TITLE
Benchmark a contiguous data representation for Sparse Polynomials

### ISSUE THREAD

**Issue by huitseeker** [lurk-lab/arecibo#61]
#38 switched the representation of sparse matrices from COO to CSR, to a slight performance benefits in operations such as SpMV. The key insight is that CSR is a representation where data for successive data in a loop is represented consecutively in memory. This makes it amenable to auto-vectorizers.

Nova uses a representation of a sparse polynomial in (coordinate, coefficient) form, where the representation of data being iterated upon is not contiguous:
https://github.com/lurk-lab/arecibo/blob/dev/src/spartan/polys/multilinear.rs#L137-L174

It's possible that switching to a contiguous memory representation (one vector for coefficients, one vector for coordinates) may bring performance benefits, and probably worth testing.

**Comment by winston-h-zhang** [comment]
I think it's unlikely this will bring much performance benefits.

The profile for `CompressedSNARK::prove` looks like:
```
CompressedSNARK::prove  6.33s ├─────────────────────────────────────────────────────────────────────────────┤
  SNARK::prove          5.86s ├───────────────────────────────────────────────────────────────────────┤
    EE::prove           5.71s     ├───────────────────────────────────────────────────────────────────┤
  SNARK::prove          461ms                                                                          ├────┤
    EE::prove           437ms                                                                           ├───┤
```
Once we enter `EE::prove` to do the IPA, which is basically 95% of the computation, sparse polynomials won't be used anymore. So any performance benefit here is likely minimal.

**Comment by huitseeker** [comment]
Closing, as this is resolved in the negative.
