### ISSUE TITLE
`supernova::RecursiveSNARK::prove_step()` shouldn't need `augmented_circuit_index` as a parameter

### ISSUE THREAD

**Issue by mpenciak** [lurk-lab/arecibo#64]
The current setup with the program counter for `supernova::RecursiveSNARK` makes it so that at each step of the proof the user has to provide an `augemented_circuit_index` to `RecursiveSNARK::prove_step()`.

`RecursiveSNARK` already internally contains the data of the program counter which has to be extracted from and then, immediately afterwards, provided as an input to `RecursiveSNARK` in the proving loop using some sort of logic similar to what is done [here](https://github.com/lurk-lab/arecibo/blob/cc71054d45855f0a027c3aaff4b9f1c072187b22/examples/nivc_nontrivial.rs#L254-L256).

If `RecursiveSNARK` internally kept track of the next augmented circuit index, it should be possible to change the signature of `prove_step` to:

```rust
  pub fn prove_step<N: NonUniformCircuit<G1, G2, C1, C2>>(
    &mut self,
    pp: &PublicParams<G1, G2, C1, C2>,
    non_uniform_circuit: &N,
    z0_primary: &[G1::Scalar],
    z0_secondary: &[G2::Scalar],
  ) -> Result<(), SuperNovaError>
```

and add the logic from the above-linked example to the `prove_step` method.

By making this change, we will probably be excluding some unusual use-cases for Supernova's NIVC, but I don't think it's excluding the main use-case where `program_counter` directly points to the next expected circuit to evaluate.

**Comment by adr1anh** [comment]
On a similar note, the `iter_base_step` takes 3 different variations of "program counter". 

The function takes three counters:
- `circuit_index: usize`: used to index into the public parameters and get the primary circuit's shape. It is the program counter for the first curve. It is also then given to the second circuit as witness to indicate which accumulator to initialize. 
- `initial_program_counter: Option<G1::Scalar>`: Indicates which function is run in the first iteration on the primary circuit. It is only used at input to the first circuit, as should be the same as `circuit_index`
- `first_augmented_circuit_index: usize`: It says which one of the primary circuits should be folded. Again, same as `circuit_index`

Unless I'm missing something, having only a single `circuit_index` would make the API much clearer.

**Comment by adr1anh** [comment]
The `iter_base_step` function can accept a `usize` as the initial `program_counter`. It would make sense then to make [initial_program_counter](https://github.com/lurk-lab/arecibo/blob/00d76e275a2b2209bf03859b97c85d64f2e4ad07/src/supernova/mod.rs#L957-L960) return a `usize` as well.
