### ISSUE TITLE
Add test of NIVC CompressedSNARK to the non-deterministic NIVC test, once available.

### ISSUE THREAD

**Issue by porcuquine** [lurk-lab/arecibo#93]
#92 left a TODO:

Add a test of compression once the NIVC CompressedSNARK lands. (https://github.com/lurk-lab/arecibo/issues/27 https://github.com/lurk-lab/arecibo/pull/80)

**Comment by huitseeker** [comment]
Fix submitted as part of #131  in 8b1df6ab2e66829955d5ec2b70bedbafdf9deeb6

**Comment by huitseeker** [comment]
Closed in #131
